-- SETANDO BANCO DE DADOS
USE dbModelDatabase
GO

-- MODO ANSI (RECOMENDADO)
SELECT * 
FROM ITENS_PEDIDO I 
INNER JOIN PRODUTOS P
ON 	I.IDPRODUTO = P.IDPRODUTO
GO

-- MODO NÃO-ANSI USANDO A CLÁUSULA WHERE
SELECT * 
FROM  ITENS_PEDIDO I, PRODUTOS P
WHERE I.IDPRODUTO = P.IDPRODUTO
GO

-- TAMBÉM É POSSÍVEL ESPECIFICAR DE QUAL TABELA A COLUNA SE REFERE
SELECT I.IDPEDIDO
        ,I.IDPRODUTO
        ,P.IDPRODUTO
        ,P.NomeProduto
FROM ITENS_PEDIDO I 
        INNER JOIN
        PRODUTOS P
ON 	I.IDPRODUTO = P.IDPRODUTO
GO
