-- SETANDO BANCO DE DADOS
USE dbModelDatabase
GO

-- FULL JOIN
SELECT * 
FROM  ITENS_PEDIDO I, PRODUTOS P
WHERE I.IDPRODUTO = P.IDPRODUTO
GO

-- EQUIJOIN
SELECT PRO.NomeProduto
	  ,C.NomeCategoria
FROM PRODUTOS PRO 
INNER JOIN CATEGORIAS C
ON PRO.IdCategoria = C.IdCategoria
GO

-- OUTER JOIN (LEFT JOIN)
SELECT *
FROM CLIENTES C 
LEFT OUTER JOIN PEDIDOS P
ON C.IdCliente = P.IdCliente
GO

SELECT *
FROM CLIENTES C 
LEFT OUTER JOIN PEDIDOS P
ON C.IdCliente = P.IdCliente
WHERE P.IDCLIENTE IS NULL
GO

-- OUTER JOIN (RIGHT JOIN)
SELECT *
FROM  PEDIDOS P 
RIGHT OUTER JOIN CLIENTES C
ON C.IdCliente = P.IdCliente
GO

SELECT *
FROM  PEDIDOS P 
RIGHT OUTER JOIN CLIENTES C
ON C.IdCliente = P.IdCliente
WHERE P.IDCLIENTE IS NULL
GO
