-- SETANDO BANCO DE DADOS
USE dbModelDatabase
GO

-- COUNT
SELECT COUNT(IDPEDIDO) AS QTD
FROM ITENS_PEDIDO
GO

SELECT COUNT(*) AS QTD
FROM ITENS_PEDIDO
GO

-- COUNT COM DISTINCT
SELECT COUNT(DISTINCT IDPEDIDO) AS QTD
FROM ITENS_PEDIDO
GO

-- PRINCIPAIS AGG. FUNCTIONS: COUNT(), MAX(), MIN(), SUM() E AVG()
SELECT COUNT(IDPRODUTO)     AS 'QTD'
      ,MAX(PRCPRODUTO)      AS 'MAX PRICE'
	  ,MIN(PRCPRODUTO)      AS 'MIN PRICE'
	  ,SUM(PRCPRODUTO)      AS 'SUM OF THE PRICES'
	  ,AVG(PRCPRODUTO)      AS 'AVERAGE OF THE PRICES'
FROM PRODUTOS
GO

-- AS AGG COLUMNS NÃO PRECISAM ESTAR NAS ESPECIFICADAS NA CLÁUSULA GROUP BY, MAS TODAS AS DEMAIS COLUNAS PRECISAM ESTAR OBRIGATORIAMENTE
SELECT I.IdPedido
      ,P.NomeProduto
	  ,COUNT(I.IDPRODUTO)   AS 'NUMBER OF PRODUCTS' 
	  ,SUM(I.QTDPEDIDA)	    AS 'AMOUNT FOR THIS PRODUCT' 
FROM ITENS_PEDIDO I INNER JOIN PRODUTOS P
ON I.IdProduto = P.IdProduto
GROUP BY I.IdPedido, P.NomeProduto
ORDER BY I.IdPedido, P.NomeProduto
GO

-- A CLÁUSULA WHERE NÃO SUPORTA AGG COLUMNS, POR TANTO PARA FAZER ESSE FILTRO É NECESSÁRIO USAR A CLÁUSULA HAVING
SELECT IDCLIENTE
      ,COUNT(IDPEDIDO) AS 'AMOUNT OF ORDERS' 
FROM PEDIDOS
GROUP BY IDCLIENTE
HAVING COUNT(IDPEDIDO) > 20
ORDER BY IDCLIENTE
GO

-- VISUALIZANDO O VALOR DOS PEDIDOS
SELECT PE.IdPedido
	  ,PRO.NomeProduto
	  ,SUM(I.QtdPedida*PRO.PrcProduto) AS 'TOTAL $$$ FOR THIS PRODUCT'
FROM PEDIDOS PE 
INNER JOIN ITENS_PEDIDO I
ON PE.IdPedido = I.IdPedido
INNER JOIN PRODUTOS PRO
 ON I.IdProduto = PRO.IdProduto
GROUP BY PE.IdPedido, PRO.NomeProduto
ORDER BY PE.IdPedido, PRO.NomeProduto
GO
