-- SETANDO BANCO DE DADOS
USE dbModelDatabase
GO

-- CRIANDO PROCEDURE SIMPLES:
CREATE PROCEDURE HELLO_WORLD
AS
BEGIN
  SELECT 'HELLO WORLD'
END
GO

-- CHAMANDO A PROCEDURE
HELLO_WORLD
GO

EXECUTE HELLO_WORLD
GO

EXEC HELLO_WORLD
GO

-- VISUALIZANDO A ESTRUTURA DA PROCEDURE
SP_HELPTEXT HELLO_WORLD
GO

-- CRIANDO PROCEDURE COM PARAMETROS
CREATE PROCEDURE ST_CALC  @X INT , @Y INT OUTPUT
AS
BEGIN
	SET @Y = @X * 2
END
GO

-- CHAMANDO A PROCEDURE
DECLARE @RESULT INT
GO

EXEC ST_CALC 20, @RESULT OUTPUT
GO

SELECT @RESULT
GO

-- REMOVENDO PROCEDURE
DROP PROCEDURE ST_CALC
GO

-- CRIANDO PROCEDURE COM CONDICIONAIS
CREATE PROCEDURE ST_GET_OBJECTS_ALL
	@OBJECTID INT,
	@NAME VARCHAR(100),
	@START_DATE DATETIME,
	@END_DATE   DATETIME
AS
BEGIN
    -- DECLARE @SQL_QUERY NVARCHAR(100)
    -- SET @SQL_QUERY = ...

	IF @OBJECTID IS NOT NULL
		SELECT *
		FROM sysobjects
		WHERE id = @OBJECTID

	IF @NAME IS NOT NULL
		SELECT *
		FROM sysobjects
		WHERE name = @NAME

	IF ( (@START_DATE IS NOT NULL) AND
	     (@END_DATE IS NOT NULL) )	
		SELECT *
		FROM sysobjects
		WHERE crdate BETWEEN @START_DATE AND @END_DATE
END
GO

-- EXECUTANDO A PROCEDURE
EXEC ST_GET_OBJECTS_ALL 5,NULL,NULL,NULL

EXEC ST_GET_OBJECTS_ALL NULL,'syspriorities',NULL,NULL

EXEC ST_GET_OBJECTS_ALL NULL
                       ,NULL
                       ,'2014-01-01'
                       ,'2014-05-30'
