-- SETANDO BANCO DE DADOS
USE dbModelDatabase
GO

-- CRIANDO TABELA PARA TESTAR O TRIGGER
CREATE TABLE TB_TEST_TRIGGER
(
	ID_TEST INT,
	NAME_TEST VARCHAR(100)
)
GO

-- INSERINDO DADOS NA TABELA
INSERT TB_TEST_TRIGGER VALUES(1,'ABC')
GO

INSERT TB_TEST_TRIGGER VALUES(2,'DEF')
GO

-- VISUALIZANDO TABELA
SELECT * FROM TB_TEST_TRIGGER
GO

-- CRIANDO TRIGGER PARA OPERAÇÃO DE INSERT
CREATE TRIGGER T_INSERT 
ON TB_TEST_TRIGGER 
FOR INSERT
--  UPDATE
--  DELETE 
AS
BEGIN
	SELECT * FROM INSERTED
END
go

-- INSERINDO DADO APÓS CRIAÇÃO DO TRIGGER
INSERT TB_TEST_TRIGGER VALUES(3,'FFF')
GO

-- DESABILITANDO/HABILITANDO UM TRIGGER
ALTER TABLE TB_TEST_TRIGGER 
DISABLE TRIGGER T_INSERT

ALTER TABLE TB_TEST_TRIGGER 
ENABLE TRIGGER T_INSERT
