-- SETANDO BANCO DE DADOS
USE dbModelDatabase
GO

-- CRIANDO TABELA QUE IRÁ RECEBER INSERTS
CREATE TABLE T1
(
	COL1 INT NOT NULL PRIMARY KEY,
	COL2 VARCHAR(10)
)
GO

-- INSERINDO NA TABELA O RESULTADO DE UMA CONSULTA
INSERT T1
SELECT TOP 10 IDCLIENTE
             ,SUBSTRING(NOMECLIENTE,1,10)
FROM CLIENTES
GO

-- VISUALIZANDO A TABELA T1
SELECT * FROM T1
GO

-- USANDO A PALAVRA-CHAVE INTO NO SELECT PARA CRIAR UMA TABELA QUE IRÁ ARMAZENAR O RESULTADO DA CONSULTA
SELECT TOP 10 IDCLIENTE
            , NOMECLIENTE
INTO T2
FROM CLIENTES
GO

-- VISUALIZANDO A TABELA T2
SELECT * FROM T2
GO
