-- VISUALIZANDO VERSÃO DO SQL SERVER
SELECT @@VERSION
GO

-- VISUALIZANDO A DATA E HORA ATUAL
SELECT GETDATE()
GO

-- SETANDO BANCO DE DADOS
USE dbModelDatabase
GO

-- VISUALIZANDO O NOME DO CLIENTE DA TABELA CLIENTES
SELECT NomeCliente
FROM CLIENTES
GO

-- VISUALIZANDO NOME DO PRODUTO DA TABELA PRODUTOS
SELECT NomeProduto
FROM PRODUTOS
GO

-- VISUALIZANDO NOME DO PRODUTO E UNIDADE DE MEDIDA
SELECT NOMEPRODUTO, UMPRODUTO
FROM PRODUTOS
GO

-- VISUALIZANDO TODAS AS COLUNAS DA TABELA DE PRODUTOS
SELECT *
FROM PEDIDOS
GO

-- APLICANDO UM APELIDO A COLUNA
SELECT GETDATE() AS DATA_ATUAL
GO

-- APLICANDO UM APELIDO A COLUNA USANDO ESPAÇO
SELECT NOMEPRODUTO [NOME ATUAL]
FROM PRODUTOS
GO
