-- SETANDO BANCO DE DADOS
USE dbModelDatabase
GO

-- VISUALIZANDO O PRODUTO QUE POSSUI O MAIOR PREÇO
SELECT IDPRODUTO
      ,PRCPRODUTO
FROM PRODUTOS
WHERE PRCPRODUTO = (SELECT MAX(PRCPRODUTO) FROM PRODUTOS)
GO

-- VISUALIZANDO PEDIDOS QUE POSSUEM UMA QTD DE ITENS MAIOR DO QUE A MÉDIA
SELECT IDPEDIDO AS 'Pedido'
      ,QtdItensPedido as 'Qtd'
FROM PEDIDOS
WHERE DataPedido BETWEEN '2020-08-01' AND '2020-08-30'
AND QtdItensPedido >= (SELECT AVG(QTDITENSPEDIDO)
                       FROM PEDIDOS   
					   WHERE DataPedido BETWEEN '2020-08-01' AND '2020-08-30')
GO

-- QUANDO UMA SUBQUERY RETORNA MAIS DE UMA LINHA É NECESSÁRIO UTILIZAR FUNÇÕES COMO IN OU EXISTS
SELECT IdPedido
      ,idCliente
	  ,QtdItensPedido
FROM PEDIDOS
WHERE QtdItensPedido > 90
AND   IdCliente IN (SELECT IdCliente
                    FROM CLIENTES
					WHERE NomeCliente LIKE 'Empresa%')
GO

-- RETORNANDO TODAS AS EMPRESAS QUE TRANSPORTARAM PEDIDOS COM 5 ITENS OU MENOS
SELECT DISTINCT A.idTransportadora, 
				C.NomeTransportadora 'Trasportadora'
FROM PEDIDOS AS A,
     (SELECT IDPEDIDO FROM ITENS_PEDIDO WHERE QtdPedida <=5) AS B,
	 TRANSPORTADORAS C
WHERE A.IdPedido = B.IdPedido
AND A.idTransportadora = C.IdTransportadora
ORDER BY A.idTransportadora
GO
