-- SETANDO BANCO DE DADOS
USE dbModelDatabase
GO

-- VISUALIZANDO DADOS SEM O DISTINCT (HAVERÃO DADOS DUPLICADOS)
SELECT UMProduto
FROM PRODUTOS
GO

-- USANDO DISTINCT PARA REMOVER DADOS DUPLICADOS
SELECT DISTINCT UMProduto
FROM PRODUTOS
GO
